// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Chat(arg1:Array<main.ChatMessage>,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function FileExists(arg1:string):Promise<boolean>;

export function FindLuaPathInConfig(arg1:string,arg2:string):Promise<string>;

export function HasClaudeKey():Promise<boolean>;

export function ListChatModels():Promise<Array<main.ModelOption>>;

export function ListTickers(arg1:string):Promise<Array<string>>;

export function PickConfigFile():Promise<string>;

export function PickDBFile():Promise<string>;

export function PickLuaFile():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function RunBacktest(arg1:string,arg2:string,arg3:string):Promise<Array<main.RunResult>>;

export function RunUserQuery(arg1:string,arg2:string):Promise<main.QueryResult>;

export function SaveClaudeKey(arg1:string):Promise<void>;

export function TickerDateRanges(arg1:string):Promise<Record<string, Array<string>>>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
