// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function FindLuaPathInConfig(arg1, arg2) {
  return window['go']['main']['App']['FindLuaPathInConfig'](arg1, arg2);
}

export function ListTickers(arg1) {
  return window['go']['main']['App']['ListTickers'](arg1);
}

export function PickConfigFile() {
  return window['go']['main']['App']['PickConfigFile']();
}

export function PickDBFile() {
  return window['go']['main']['App']['PickDBFile']();
}

export function PickLuaFile() {
  return window['go']['main']['App']['PickLuaFile']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RunBacktest(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunBacktest'](arg1, arg2, arg3);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
