// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FileExists(arg1:string):Promise<boolean>;

export function FindLuaPathInConfig(arg1:string,arg2:string):Promise<string>;

export function ListTickers(arg1:string):Promise<Array<string>>;

export function PickConfigFile():Promise<string>;

export function PickDBFile():Promise<string>;

export function PickLuaFile():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function RunBacktest(arg1:string,arg2:string,arg3:string):Promise<Array<main.RunResult>>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
